//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maanfee.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maanfee.Dashboard.Resources.DashboardResource", typeof(DashboardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has been already inserted.
        /// </summary>
        public static string MessageCannotInsertDuplicate {
            get {
                return ResourceManager.GetString("MessageCannotInsertDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change is not possible.
        /// </summary>
        public static string MessageChangeIsNotPossible {
            get {
                return ResourceManager.GetString("MessageChangeIsNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version is {0} and the new version is {1}..
        /// </summary>
        public static string MessageCompareReleases {
            get {
                return ResourceManager.GetString("MessageCompareReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is used elsewhere and cannot be deleted.
        /// </summary>
        public static string MessageDeleteConstraint {
            get {
                return ResourceManager.GetString("MessageDeleteConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string MessageDeletedSuccessfully {
            get {
                return ResourceManager.GetString("MessageDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment of documentation is mandatory..
        /// </summary>
        public static string MessageDocumentAttachment {
            get {
                return ResourceManager.GetString("MessageDocumentAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this message again.
        /// </summary>
        public static string MessageDontShow {
            get {
                return ResourceManager.GetString("MessageDontShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is large.The file {0} could not be loaded.
        /// </summary>
        public static string MessageFileSizeError {
            get {
                return ResourceManager.GetString("MessageFileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral code is not valid.
        /// </summary>
        public static string MessageInvalidReferralCode {
            get {
                return ResourceManager.GetString("MessageInvalidReferralCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is invalid,It can only contain letters or digits.
        /// </summary>
        public static string MessageInvalidUsername {
            get {
                return ResourceManager.GetString("MessageInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already taken.
        /// </summary>
        public static string MessageItemAlreadyTaken {
            get {
                return ResourceManager.GetString("MessageItemAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of allowed files is {0} while you selected {1} files.
        /// </summary>
        public static string MessageMaximumNumberOfFiles {
            get {
                return ResourceManager.GetString("MessageMaximumNumberOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new and improved version is now available.
        /// </summary>
        public static string MessageNewRelease {
            get {
                return ResourceManager.GetString("MessageNewRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string MessageNoMatchingRecordsFound {
            get {
                return ResourceManager.GetString("MessageNoMatchingRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key limitation Please change the code.
        /// </summary>
        public static string MessagePrimaryKeyConstraint {
            get {
                return ResourceManager.GetString("MessagePrimaryKeyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Considering that the role is not defined for the user, it is not possible to use some parts of the system..
        /// </summary>
        public static string MessageRoleIsNotDefined {
            get {
                return ResourceManager.GetString("MessageRoleIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string MessageSavedSuccessfully {
            get {
                return ResourceManager.GetString("MessageSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with the service is not possible.
        /// </summary>
        public static string MessageServiceCommunicationError {
            get {
                return ResourceManager.GetString("MessageServiceCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item could not be a subset of itself.
        /// </summary>
        public static string MessageThisItemCouldNoBeASubsetOfItself {
            get {
                return ResourceManager.GetString("MessageThisItemCouldNoBeASubsetOfItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see the changes please click here..
        /// </summary>
        public static string MessageToSeeChanges {
            get {
                return ResourceManager.GetString("MessageToSeeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send request.
        /// </summary>
        public static string MessageUnableToSendRequest {
            get {
                return ResourceManager.GetString("MessageUnableToSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not exsist.
        /// </summary>
        public static string MessageUserIsNotExsist {
            get {
                return ResourceManager.GetString("MessageUserIsNotExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new message has been sent by {0}.
        /// </summary>
        public static string SignalRReceiveChatNotification {
            get {
                return ResourceManager.GetString("SignalRReceiveChatNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string StringAbout {
            get {
                return ResourceManager.GetString("StringAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&amp;apos;ve read and accept Terms of Service..
        /// </summary>
        public static string StringAcceptTerms {
            get {
                return ResourceManager.GetString("StringAcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string StringAccessDenied {
            get {
                return ResourceManager.GetString("StringAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you don have permission to access this resource.
        /// </summary>
        public static string StringAccessDenied2 {
            get {
                return ResourceManager.GetString("StringAccessDenied2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach out your system administrator to gain access.
        /// </summary>
        public static string StringAccessDenied3 {
            get {
                return ResourceManager.GetString("StringAccessDenied3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string StringAccount {
            get {
                return ResourceManager.GetString("StringAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string StringAction {
            get {
                return ResourceManager.GetString("StringAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add features.
        /// </summary>
        public static string StringAddFeatures {
            get {
                return ResourceManager.GetString("StringAddFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string StringAdministrator {
            get {
                return ResourceManager.GetString("StringAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        public static string StringAdvancedSearch {
            get {
                return ResourceManager.GetString("StringAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string StringAlert {
            get {
                return ResourceManager.GetString("StringAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string StringAllItemsText {
            get {
                return ResourceManager.GetString("StringAllItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string StringAlreadyAccount {
            get {
                return ResourceManager.GetString("StringAlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this item?.
        /// </summary>
        public static string StringAreYouSureToDeleteThisItem {
            get {
                return ResourceManager.GetString("StringAreYouSureToDeleteThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string StringAuthentication {
            get {
                return ResourceManager.GetString("StringAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string StringAvatar {
            get {
                return ResourceManager.GetString("StringAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string StringBytes {
            get {
                return ResourceManager.GetString("StringBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StringCancel {
            get {
                return ResourceManager.GetString("StringCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string StringChangePassword {
            get {
                return ResourceManager.GetString("StringChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string StringChat {
            get {
                return ResourceManager.GetString("StringChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گپ.
        /// </summary>
        public static string StringChats {
            get {
                return ResourceManager.GetString("StringChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cache.
        /// </summary>
        public static string StringClearCache {
            get {
                return ResourceManager.GetString("StringClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string StringCode {
            get {
                return ResourceManager.GetString("StringCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string StringColor {
            get {
                return ResourceManager.GetString("StringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string StringComment {
            get {
                return ResourceManager.GetString("StringComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        public static string StringCommunications {
            get {
                return ResourceManager.GetString("StringCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string StringCommunity {
            get {
                return ResourceManager.GetString("StringCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string StringConfiguration {
            get {
                return ResourceManager.GetString("StringConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string StringConfirmation {
            get {
                return ResourceManager.GetString("StringConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string StringConfirmNewPassword {
            get {
                return ResourceManager.GetString("StringConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string StringConfirmPassword {
            get {
                return ResourceManager.GetString("StringConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string StringCreate {
            get {
                return ResourceManager.GetString("StringCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture Information.
        /// </summary>
        public static string StringCultureInformation {
            get {
                return ResourceManager.GetString("StringCultureInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string StringCurrentPassword {
            get {
                return ResourceManager.GetString("StringCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string StringDashboard {
            get {
                return ResourceManager.GetString("StringDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string StringDatabase {
            get {
                return ResourceManager.GetString("StringDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string StringDate {
            get {
                return ResourceManager.GetString("StringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string StringDelete {
            get {
                return ResourceManager.GetString("StringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dense.
        /// </summary>
        public static string StringDense {
            get {
                return ResourceManager.GetString("StringDense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string StringDepartment {
            get {
                return ResourceManager.GetString("StringDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string StringDescription {
            get {
                return ResourceManager.GetString("StringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string StringDetails {
            get {
                return ResourceManager.GetString("StringDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string StringDiagram {
            get {
                return ResourceManager.GetString("StringDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string StringDocuments {
            get {
                return ResourceManager.GetString("StringDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string StringDontAccount {
            get {
                return ResourceManager.GetString("StringDontAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net.
        /// </summary>
        public static string StringdotNet {
            get {
                return ResourceManager.GetString("StringdotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string StringEdit {
            get {
                return ResourceManager.GetString("StringEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string StringEncryption {
            get {
                return ResourceManager.GetString("StringEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string StringExportExcel {
            get {
                return ResourceManager.GetString("StringExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Name.
        /// </summary>
        public static string StringFatherName {
            get {
                return ResourceManager.GetString("StringFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string StringFile {
            get {
                return ResourceManager.GetString("StringFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string StringFirstName {
            get {
                return ResourceManager.GetString("StringFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed header.
        /// </summary>
        public static string StringFixedHeader {
            get {
                return ResourceManager.GetString("StringFixedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string StringFonts {
            get {
                return ResourceManager.GetString("StringFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string StringForgotPassword {
            get {
                return ResourceManager.GetString("StringForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        public static string StringFramework {
            get {
                return ResourceManager.GetString("StringFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string StringGender {
            get {
                return ResourceManager.GetString("StringGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string StringGroup {
            get {
                return ResourceManager.GetString("StringGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has changed.
        /// </summary>
        public static string StringHasChanged {
            get {
                return ResourceManager.GetString("StringHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string StringImage {
            get {
                return ResourceManager.GetString("StringImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {first_item}-{last_item} of {all_items}.
        /// </summary>
        public static string StringInfoFormat {
            get {
                return ResourceManager.GetString("StringInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string StringInformation {
            get {
                return ResourceManager.GetString("StringInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string StringIsActive {
            get {
                return ResourceManager.GetString("StringIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string StringLastName {
            get {
                return ResourceManager.GetString("StringLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string StringList {
            get {
                return ResourceManager.GetString("StringList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string StringLoading {
            get {
                return ResourceManager.GetString("StringLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string StringLogout {
            get {
                return ResourceManager.GetString("StringLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout confirmation.
        /// </summary>
        public static string StringLogoutConfirmation {
            get {
                return ResourceManager.GetString("StringLogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permission.
        /// </summary>
        public static string StringManagePermission {
            get {
                return ResourceManager.GetString("StringManagePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum file size for uploading should be {0} KB.
        /// </summary>
        public static string StringMaximumFileSize {
            get {
                return ResourceManager.GetString("StringMaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message....
        /// </summary>
        public static string StringMessageEnterYourMessage {
            get {
                return ResourceManager.GetString("StringMessageEnterYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string StringModuleName {
            get {
                return ResourceManager.GetString("StringModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National/Passport code.
        /// </summary>
        public static string StringNationalCode {
            get {
                return ResourceManager.GetString("StringNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string StringNewPassword {
            get {
                return ResourceManager.GetString("StringNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Release.
        /// </summary>
        public static string StringNewVersionReleased {
            get {
                return ResourceManager.GetString("StringNewVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized name.
        /// </summary>
        public static string StringNormalizedName {
            get {
                return ResourceManager.GetString("StringNormalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string StringNotifications {
            get {
                return ResourceManager.GetString("StringNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s).
        /// </summary>
        public static string StringNumberOfFiles {
            get {
                return ResourceManager.GetString("StringNumberOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational chart.
        /// </summary>
        public static string StringOrganizationalChart {
            get {
                return ResourceManager.GetString("StringOrganizationalChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found..
        /// </summary>
        public static string StringPageNotExist {
            get {
                return ResourceManager.GetString("StringPageNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string StringParent {
            get {
                return ResourceManager.GetString("StringParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string StringPath {
            get {
                return ResourceManager.GetString("StringPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string StringPermission {
            get {
                return ResourceManager.GetString("StringPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal code.
        /// </summary>
        public static string StringPersonalCode {
            get {
                return ResourceManager.GetString("StringPersonalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        public static string StringPersonalInformation {
            get {
                return ResourceManager.GetString("StringPersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string StringPhoneNumber {
            get {
                return ResourceManager.GetString("StringPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string StringPost {
            get {
                return ResourceManager.GetString("StringPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string StringPrint {
            get {
                return ResourceManager.GetString("StringPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string StringProcessing {
            get {
                return ResourceManager.GetString("StringProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick search.
        /// </summary>
        public static string StringQuickSearch {
            get {
                return ResourceManager.GetString("StringQuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick-Start guide.
        /// </summary>
        public static string StringQuickStartGuide {
            get {
                return ResourceManager.GetString("StringQuickStartGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to Logout?.
        /// </summary>
        public static string StringReallyLogout {
            get {
                return ResourceManager.GetString("StringReallyLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string StringRegister {
            get {
                return ResourceManager.GetString("StringRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        public static string StringRegisterHere {
            get {
                return ResourceManager.GetString("StringRegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrant name.
        /// </summary>
        public static string StringRegistrantName {
            get {
                return ResourceManager.GetString("StringRegistrantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string StringRegistrationDate {
            get {
                return ResourceManager.GetString("StringRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string StringRelease {
            get {
                return ResourceManager.GetString("StringRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released on.
        /// </summary>
        public static string StringReleasedOn {
            get {
                return ResourceManager.GetString("StringReleasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released versions.
        /// </summary>
        public static string StringReleasedVersions {
            get {
                return ResourceManager.GetString("StringReleasedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release note type.
        /// </summary>
        public static string StringReleaseNoteType {
            get {
                return ResourceManager.GetString("StringReleaseNoteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Time:.
        /// </summary>
        public static string StringReleaseTime {
            get {
                return ResourceManager.GetString("StringReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release type.
        /// </summary>
        public static string StringReleaseType {
            get {
                return ResourceManager.GetString("StringReleaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string StringReload {
            get {
                return ResourceManager.GetString("StringReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string StringReports {
            get {
                return ResourceManager.GetString("StringReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string StringRequired {
            get {
                return ResourceManager.GetString("StringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string StringResources {
            get {
                return ResourceManager.GetString("StringResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string StringRole {
            get {
                return ResourceManager.GetString("StringRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page:.
        /// </summary>
        public static string StringRowsPerPage {
            get {
                return ResourceManager.GetString("StringRowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in fullscreen mode at startup.
        /// </summary>
        public static string StringRunFullscreenMode {
            get {
                return ResourceManager.GetString("StringRunFullscreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll.
        /// </summary>
        public static string StringScroll {
            get {
                return ResourceManager.GetString("StringScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string StringSearch {
            get {
                return ResourceManager.GetString("StringSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string StringSelect {
            get {
                return ResourceManager.GetString("StringSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string StringSelectAll {
            get {
                return ResourceManager.GetString("StringSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string StringSend {
            get {
                return ResourceManager.GetString("StringSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string StringSettings {
            get {
                return ResourceManager.GetString("StringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string StringSignin {
            get {
                return ResourceManager.GetString("StringSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your credentials.
        /// </summary>
        public static string StringSigninDescription {
            get {
                return ResourceManager.GetString("StringSigninDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string StringSourceCode {
            get {
                return ResourceManager.GetString("StringSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of project.
        /// </summary>
        public static string StringStartofProject {
            get {
                return ResourceManager.GetString("StringStartofProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StringStatus {
            get {
                return ResourceManager.GetString("StringStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StringStorage {
            get {
                return ResourceManager.GetString("StringStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string StringSummary {
            get {
                return ResourceManager.GetString("StringSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string StringSupport {
            get {
                return ResourceManager.GetString("StringSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger.
        /// </summary>
        public static string StringSwagger {
            get {
                return ResourceManager.GetString("StringSwagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string StringTest {
            get {
                return ResourceManager.GetString("StringTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string StringTheme {
            get {
                return ResourceManager.GetString("StringTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string StringTicket {
            get {
                return ResourceManager.GetString("StringTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string StringTitle {
            get {
                return ResourceManager.GetString("StringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle dark mode.
        /// </summary>
        public static string StringToggleDarkMode {
            get {
                return ResourceManager.GetString("StringToggleDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to fullscreen-exit fullscreen.
        /// </summary>
        public static string StringToggleFullscreen {
            get {
                return ResourceManager.GetString("StringToggleFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle right-to-left/left-to-right.
        /// </summary>
        public static string StringToggleRTL {
            get {
                return ResourceManager.GetString("StringToggleRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string StringType {
            get {
                return ResourceManager.GetString("StringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchanged.
        /// </summary>
        public static string StringUnchanged {
            get {
                return ResourceManager.GetString("StringUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        public static string StringUploadFiles {
            get {
                return ResourceManager.GetString("StringUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string StringUser {
            get {
                return ResourceManager.GetString("StringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users management.
        /// </summary>
        public static string StringUserManagement {
            get {
                return ResourceManager.GetString("StringUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string StringUserName {
            get {
                return ResourceManager.GetString("StringUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string StringUserProfile {
            get {
                return ResourceManager.GetString("StringUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string StringUsers {
            get {
                return ResourceManager.GetString("StringUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string StringVersion {
            get {
                return ResourceManager.GetString("StringVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string StringWelcome {
            get {
                return ResourceManager.GetString("StringWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s Changed.
        /// </summary>
        public static string StringWhatsChanged {
            get {
                return ResourceManager.GetString("StringWhatsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alternate user cannot be the same as the acting user.
        /// </summary>
        public static string ValidationAlternateUser {
            get {
                return ResourceManager.GetString("ValidationAlternateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered for field {0} is invalid.
        /// </summary>
        public static string ValidationInvalidValue {
            get {
                return ResourceManager.GetString("ValidationInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient of the document is not allowed to sign.
        /// </summary>
        public static string ValidationNotAllowedToSign {
            get {
                return ResourceManager.GetString("ValidationNotAllowedToSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} must be between {1} and {2}..
        /// </summary>
        public static string ValidationNumberRange {
            get {
                return ResourceManager.GetString("ValidationNumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        public static string ValidationPasswordConfirm {
            get {
                return ResourceManager.GetString("ValidationPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only positive numbers are allowed.
        /// </summary>
        public static string ValidationPositiveNumbers {
            get {
                return ResourceManager.GetString("ValidationPositiveNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receiving and sending user cannot be the same.
        /// </summary>
        public static string ValidationReceivingSendingUserCannotBeTheSame {
            get {
                return ResourceManager.GetString("ValidationReceivingSendingUserCannotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be {1} at least {2} characters long..
        /// </summary>
        public static string ValidationStringLength {
            get {
                return ResourceManager.GetString("ValidationStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} value must be {1}.
        /// </summary>
        public static string ValidationValueValidation {
            get {
                return ResourceManager.GetString("ValidationValueValidation", resourceCulture);
            }
        }
    }
}
