<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--**********************************************-->
    <TieredPGO>true</TieredPGO>
    <DebugType>none</DebugType>
    <!--**********************************************-->
    <ScopedCssEnabled>true</ScopedCssEnabled>
    <EnableDefaultScopedCssItems>true</EnableDefaultScopedCssItems>
    <!--**********************************************-->
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\DashboardAPI\Maanfee.Dashboard.Views.Core\Maanfee.Dashboard.Views.Core.csproj" />
	</ItemGroup>

</Project>
